"""
Print a CSS block for Lute's Settings -> Custom Styles box, giving
closed-class grammar tokens (noun class prefixes, verb subject
prefixes, TAM markers, object markers, and extension+terminal-vowel
combinations) a distinct look before you've marked them "known".

This is purely a presentation nicety -- it doesn't touch Lute core.
Every reading-pane span carries a data-text attribute with its exact
token text (see lute/templates/read/textitem.html), so plain CSS
attribute selectors can target our own closed, enumerable set of
grammar-token strings directly. See lute-shona's DESIGN.md section 8
for the full mechanism.

Usage:
    python scripts/generate_css.py > xhosa_grammar.css
    # then paste xhosa_grammar.css into Lute: Settings -> Custom Styles
"""

from lute_xhosa_parser.rules import (
    NOUN_CLASS_PREFIXES,
    OBJECT_MARKERS,
    PAST_SUBJECT_PREFIXES,
    TAM_MARKERS,
    TERMINAL_VOWELS,
    VERB_EXTENSIONS,
    VERB_SUBJECT_PREFIXES,
)


def grammar_token_forms():
    "All closed-class surface forms our parser can emit as a standalone grammar token."
    forms = set()
    forms.update(prefix for prefix, _class_id in NOUN_CLASS_PREFIXES)
    forms.update(VERB_SUBJECT_PREFIXES)
    forms.update(PAST_SUBJECT_PREFIXES)
    forms.update(TAM_MARKERS)
    forms.update(OBJECT_MARKERS)
    for ext in VERB_EXTENSIONS:
        for tv in TERMINAL_VOWELS:
            forms.add(ext + tv)
    return sorted(forms)


def main():
    selectors = ",\n".join(f'span[data-text="{form}" i]' for form in grammar_token_forms())
    css = f"""/* isiXhosa grammar-token highlighting, generated by scripts/generate_css.py.
   Paste into Lute: Settings -> Custom Styles.
   Matches closed-class affixes (noun class prefixes, verb subject
   prefixes, TAM markers, object markers, extension+terminal-vowel
   combinations) by exact token text -- roots are open-class and
   intentionally untouched, so they keep the default look. */
{selectors} {{
  font-weight: 600;
  color: #7a4fb5;
}}
"""
    print(css)


if __name__ == "__main__":
    main()
